version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      rmb:
        patterns:
          - "org.folio*"
          - "*vertx*"
      plugins:
        patterns:
          - "*plugin*"
          - "*checkstyle*"
      development:
        dependency-type: "development"
        patterns:
          - "*testcontainers*"
          - "*joda-time*"
          - "*hamcrest*"
          - "*mockito*"
          - "*JUnitParams*"
          - "*wiremock*"
          - "*rest-assured*"
          - "*awaitility*"
      production:
        dependency-type: "production"
        patterns:
          - "*log4j*"
          - "*lombok*"
          - "*caffeine*"
          - "*aspectj*"
          - "*marc4j*"
          - "*commons-lang*"