version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
    groups:
      dev-deps:
        dependency-type: "development"
      prod-deps:
        dependency-type: "production"