version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    commit-message:
      prefix: fix
      include: scope
    groups:
      all-deps:
        patterns:
          - "*"