stages:
- name: Clone submodules
  steps:
  - runScriptConfig:
      image: alpine/git
      shellScript: git submodule update --init --recursive
- name: Build
  steps:
  - runScriptConfig:
      image: grizzlysoftware/maven-non-root:3.6.2-11.0.4-jdk-stretch
      shellScript: mvn package -DskipTests
- name: Build Docker with DIND
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-inventory-storage:folijet-${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-gh7sb:folijet-helmcharts-mod-inventory-storage
      version: 0.1.34
      answers:
        image.repository: docker.dev.folio.org/mod-inventory-storage
        image.tag: folijet-${CICD_EXECUTION_SEQUENCE}
      targetNamespace: folijet
      name: mod-inventory-storage
timeout: 60
notification: {}
