stages:
- name: Clone submodules
  steps:
  - runScriptConfig:
       image: alpine/git
       shellScript: git submodule update --init --recursive
- name: Build
  steps:
  - runScriptConfig:
      image: maven:3.6-adoptopenjdk-11
      shellScript: mvn package -DskipTests
- name: Build Docker
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: docker.dev.folio.org/mod-inventory-storage:gulfstream-latest
      pushRemote: true
      registry: docker.dev.folio.org
- name: Deploy
  steps:
  - applyAppConfig:
      catalogTemplate: p-d9vmc:gulfstream-helmcharts-mod-inventory-storage
      version: 0.1.9
      answers:
        image.repository: docker.dev.folio.org/mod-inventory-storage
        image.tag: gulfstream-latest
      name: mod-inventory-storage
      targetNamespace: gulfstream
timeout: 60
branch:
  include:
  - gulfstream-rancher
notification: {}
