#%RAML 0.8
title: Knowledge Base
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost:9401

documentation:
  - title: Knowledge Base API
    content: <b>Defines the baseline resources provided by a knowledge base module implementation</b>

schemas:
 - instance: !include schema/instance.json
 - instances: !include schema/instances.json

traits:
 - secured: !include traits/auth.raml
 - language: !include traits/language.raml

resourceTypes:
 - collection: !include types/collection.raml

/knowledge-base:
    /instance:
      displayName: Instances
      type:
        collection:
          exampleCollection: !include  examples/instances_get.json
          schemaCollection: instances
          schemaItem: instance
          exampleItem: !include  examples/instance_get.json

      get:
        queryParameters:
          partialName:
            displayName: Partial Title
            type: string
            description: text to search for within the title of instances
            example: partialTitle="Advanced Manufacturing"
            required: false
          identifier:
            displayName: Identifier
            type: string
            description: identifier to search instances for
            example: isbn="9781466636897"
            required: false
      post:
        body:
          application/json:
            schema: !include schema/instance_create.json
            example: !include  examples/instance_post.json
        responses:
          201:
      /metadata:
        displayName: JSON-LD Metadata for Instance Resources
        get:
          responses:
            200:
              body:
                application/json:
                  example: !include examples/instance_metadata_get.json
