version: "3.9"

services:
  postgres:
    container_name: postgres_mod-inventory-storage
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: "/data/postgres"
    networks:
      - mod-inventory-storage-local

  pgadmin:
    container_name: pgadmin_mod-inventory-storage
    image: dpage/pgadmin4:8.13
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - mod-inventory-storage-local

  kafka:
    container_name: kafka_mod-inventory-storage
    image: apache/kafka-native
    networks:
      - mod-inventory-storage-local
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      # Configure listeners for both docker and host communication
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT
      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      # Listener to use for broker-to-broker communication
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
      # Required for a single node cluster
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui_mod-inventory-storage
    image: ghcr.io/kafbat/kafka-ui:latest
    networks:
      - mod-inventory-storage-local
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    depends_on:
      - kafka

  mod-inventory-storage:
    container_name: mod-inventory-storage
    image: dev.folio/mod-inventory-storage
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "5005:5005"
    environment:
      ENV: ${ENV}
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      REPLICATION_FACTOR: ${REPLICATION_FACTOR}
      DB_USERNAME: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      JAVA_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
    depends_on:
      - "postgres"
      - "kafka"
    networks:
      - mod-inventory-storage-local

networks:
  mod-inventory-storage-local:
    driver: "bridge"

volumes:
  pgadmin-data:
    driver: "local"
  postgres-data:
    driver: "local"
