version: "3.9"

services:
  postgres:
    container_name: postgres_mod-inventory-storage
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/data/postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
      PGDATA: "/data/postgres"
    networks:
      - mod-inventory-storage-local

  pgadmin:
    container_name: pgadmin_mod-inventory-storage
    image: dpage/pgadmin4:6.7
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - "pgadmin-data:/var/lib/pgadmin"
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    networks:
      - mod-inventory-storage-local

  zookeeper:
    container_name: zookeeper_mod-inventory-storage
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - mod-inventory-storage-local

  kafka:
    container_name: kafka_mod-inventory-storage
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://:9092,LOCAL://localhost:29092"
      KAFKA_BROKER_ID: "1"
      KAFKA_LOG_RETENTION_HOURS: "-1"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_LISTENERS: "INTERNAL://:9092,LOCAL://:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_LOG_RETENTION_BYTES: "-1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "LOCAL:PLAINTEXT,INTERNAL:PLAINTEXT"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    depends_on:
      - zookeeper
    networks:
      - mod-inventory-storage-local

  kafka-ui:
    container_name: kafka-ui_mod-inventory-storage
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      KAFKA_CLUSTERS_0_JMXPORT: 9997
    networks:
      - mod-inventory-storage-local

  mod-inventory-storage:
    container_name: mod-inventory-storage
    image: dev.folio/mod-inventory-storage
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "5005:5005"
    environment:
      ENV: ${ENV}
      KAFKA_HOST: ${KAFKA_HOST}
      KAFKA_PORT: ${KAFKA_PORT}
      REPLICATION_FACTOR: ${REPLICATION_FACTOR}
      DB_USERNAME: ${DB_USERNAME}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      JAVA_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT}"
    depends_on:
      - "postgres"
      - "kafka"
    networks:
      - mod-inventory-storage-local

networks:
  mod-inventory-storage-local:
    driver: "bridge"

volumes:
  pgadmin-data:
    driver: "local"
  postgres-data:
    driver: "local"
