#%RAML 1.0
title: Authority Storage
version: v1.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Authority Storage API
    content: <b>Storage for authorities in the inventory</b>

types:
  authorities: !include authorities/authorities.json
  authority: !include authorities/authority.json
  errors: !include raml-util/schemas/errors.schema

traits:
  language: !include raml-util/traits/language.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  authority-collection: !include authorities/authority-collection.raml

/authority-storage:
  /authorities:
        displayName: Authorities
        type:
          collection:
            exampleCollection: !include  examples/authorities.json
            schemaCollection: authorities
            schemaItem: authority
            exampleItem: !include  examples/authority.json
        get:
          is: [pageable,
             searchable: {description: "using CQL",
                            example: "personalName=\"root\""},
              ]
        post:
          is: [validate]
        delete:
          is: [language]
          responses:
            204:
              description: "All authorities deleted"
            500:
              description: "Internal server error, e.g. due to misconfiguration"
              body:
                text/plain:
                  example: "Internal server error, contact administrator"
        /{authorityId}:
          type:
            authority-collection:
              exampleAuthority: !include examples/authority.json
              schema: authority
          get:
        /batch:
          post:
            description: "Update authorities by authorities from file"
            queryParameters:
              authoritiesFilePath:
                description: File system path to file with authorities (one json authority per line)
                type: string
                required: true
              batchSize:
                description: Batch size which is used to write multiple authorities to database at once
                type: integer
                required: false
                default: 100
                minimum: 10
                maximum: 2147483647
