#%RAML 1.0
title: Reindex authorities
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Authority reindex
    content: Reindex authorities by generating domain events for them

types:
  reindexJob: !include reindex/get-job-by-id-response.json
  reindexJobs: !include reindex/reindex-jobs.json
  errors: !include raml-util/schemas/errors.schema

traits:
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

/authority-storage/reindex:
  displayName: Reindex authorities
  post:
    description: Submit a reindex job
    responses:
      200:
        description: Reindex job has been submitted
        body:
          application/json:
            type: reindexJob
      500:
        description: Internal server error
        body:
          text/plain:
            example: Internal server error
  get:
    is: [
      searchable: { description: "with valid searchable fields", example: "name=aaa" },
      pageable
    ]
    description: Get all reindex jobs
    responses:
      200:
        description: All reindex jobs returned
        body:
          application/json:
            type: reindexJobs
      500:
        description: Internal server error
        body:
          text/plain:
            example: Internal server error
  /{id}:
    get:
      description: Get reindex job by id
      responses:
        200:
          description: Reindex job has returned
          body:
            application/json:
              type: reindexJob
        404:
          description: Reindex job with id not found
          body:
            text/plain:
              example: Not found
        500:
          description: Internal server error
          body:
            text/plain:
              example: Internal server error
    delete:
      description: Cancell reindex job by id
      responses:
        204:
          description: Reindex job has been cancelled
        404:
          description: Reindex job with id not found
          body:
            text/plain:
              example: Not found
        500:
          description: Internal server error
          body:
            text/plain:
              example: Internal server error
