#%RAML 1.0
title: Composite bound-with API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://github.com/org/folio/mod-inventory-storage

documentation:
  - title: Composite bound-with API
    content: API call to create and/or delete some or all parts of a bound-with.

types:
  boundWith: !include boundWith.json
  boundWiths: !include boundWiths.json
  errors: !include raml-util/schemas/errors.schema

traits:
  language: !include raml-util/traits/language.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/inventory-storage/bound-withs:
  type:
    collection:
      schemaItem: boundWith
      exampleItem: !include examples/boundWith.json
      exampleCollection: !include examples/boundWiths.json
      schemaCollection: boundWiths
  put:
    description: Manage one or more parts of a bound-with item
    body:
      application/json:
        description: ID of the bound-with Item and IDs of the holdings within it.
        type: boundWith
    responses:
      204:
        description: No content; updates processed.
      400:
        description: Constraint violation; referenced Item and/or holdings were not found.
        body:
          text/plain:
            example: "Item 667e044f-173c-4445-8293-45a78ef49ace not found."
      422:
        description: Schema violation, i.e. missing mandatory property.
        body:
          application/json:
            example: {"errors":[{"message":"must not be null","type":"1","code":"javax.validation.constraints.NotNull.message","parameters":[{"key":"itemId","value":"null"}]}]}



