#%RAML 1.0
title: Classification Types API
version: v1.2
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Classification Types API
    content: This documents the API calls that can be made to query and manage classification qualifier resource types

types:
  classificationType: !include schemas/classification-types/classificationtype.json
  classificationTypes: !include schemas/classification-types/classificationtypes.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-delete-only: !include raml-util/rtypes/get-delete.raml

/classification-types:
  type:
    collection:
      exampleCollection: !include examples/classificationtypes.json
      exampleItem: !include examples/classificationtype.json
      schemaCollection: classificationTypes
      schemaItem: classificationType
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of classification qualifiers
  post:
    description: Create a new classification type
    is: [validate]
  /{classificationTypeId}:
    description: Pass in the classification type id
    type:
      collection-item:
        exampleItem: !include examples/classificationtype.json
        schema: classificationType

