#%RAML 1.0
title: Contributor Types API
version: v2.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Contributor Types API
    content: This documents the API calls that can be made to query and manage contributor types

types:
  contributorType: !include schemas/contributor-types/contributortype.json
  contributorTypes: !include schemas/contributor-types/contributortypes.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/contributor-types:
  type:
    collection:
      exampleCollection: !include examples/contributortypes.json
      exampleItem: !include examples/contributortype.json
      schemaCollection: contributorTypes
      schemaItem: contributorType
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of contributor types
  post:
    description: Create a new contributor type
    is: [validate]
  /{contributorTypeId}:
    description: Pass in the contributor type id
    type:
      collection-item:
        exampleItem: !include examples/contributortype.json
        schema: contributorType

