#%RAML 1.0
title: Contributor Name Types API
version: v1.3
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Contributor Name Types API
    content: This documents the API calls that can be made to query and manage contributor name types

types:
  contributorNameType: !include schemas/contributor-name-types/contributornametype.json
  contributorNameTypes: !include schemas/contributor-name-types/contributornametypes.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-delete-only: !include raml-util/rtypes/get-delete.raml

/contributor-name-types:
  type:
    collection:
      exampleCollection: !include examples/contributornametypes.json
      exampleItem: !include examples/contributornametype.json
      schemaCollection: contributorNameTypes
      schemaItem: contributorNameType
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of contributor name types
  post:
    description: Create a new contributor name type
    is: [validate]
  /{contributorNameTypeId}:
    description: Pass in the contributor name type id
    type:
      collection-item:
        exampleItem: !include examples/contributornametype.json
        schema: contributorNameType
