#%RAML 1.0
title: Holdings Records Sources API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Holdings Records Sources API
    content: This documents the API calls that can be made to query and manage holdings records sources

types:
  holdingsRecordsSource: !include holdings-sources/holdingsRecordsSource.json
  holdingsRecordsSources: !include holdings-sources/holdingsRecordsSources.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/holdings-sources:
  type:
    collection:
      exampleCollection: !include examples/holdings-sources/holdingsRecordsSources.json
      exampleItem: !include examples/holdings-sources/holdingsRecordsSource.json
      schemaCollection: holdingsRecordsSources
      schemaItem: holdingsRecordsSource
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of holdings records sources
  post:
    description: Create a new holdings records source
    is: [validate]
  /{id}:
    description: Pass in the holdings records source id
    type:
      collection-item:
        exampleItem: !include examples/holdings-sources/holdingsRecordsSource.json
        schema: holdingsRecordsSource
