#%RAML 1.0
title: Holdings Storage
version: v6.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Holdings Records Storage API
    content: <b>Storage for holdings in the inventory</b>

types:
  holdingsRecord: !include holdings-storage/holdingsRecord.json
  holdingsRecords: !include holdings-storage/holdingsRecords.json
  holdingsRecordView: !include holdings-storage/holdingsRecordView.json
  holdingsRecordViews: !include holdings-storage/holdingsRecordViews.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/holdings-storage:
  /holdings:
    displayName: Holdings
    type:
      collection:
        exampleCollection: !include examples/holdings-storage/holdingsRecords_get.json
        schemaCollection: holdingsRecordViews
        schemaItem: holdingsRecordView
        exampleItem: !include examples/holdings-storage/holdingsRecord_get.json
    get:
      is: [pageable,
           searchable: {description: "by instance ID (using CQL)",
                        example: "instanceId=\"2b94c631-fca9-4892-a730-03ee529ffe2a\""},
          ]
    post:
      is: [validate]
      body:
        application/json:
          type: holdingsRecord
          example:
            strict: false
            value: !include examples/holdings-storage/holdingsRecord_get.json
    delete:
      is: [searchable: { description: "CQL to select holdings to delete, use cql.allRecords=1 to delete all", example: "callNumber==\"123-0*\"" } ]
      responses:
        204:
          description: "Selected holdings deleted"
        400:
          description: "Bad request, e.g. malformed query parameter"
          body:
            text/plain:
              example: "query parameter is empty"
        500:
          description: "Internal server error, e.g. due to misconfiguration"
          body:
            text/plain:
              example: "Internal server error, contact administrator"
    /{holdingsRecordId}:
      type:
        collection-item:
          exampleItem: !include examples/holdings-storage/holdingsRecord_get.json
          schema: holdingsRecordView
      get:
        responses:
          200:
            body:
              application/json:
                type: holdingsRecord
            description: |
              Get Holdings Record by holdingsRecordId
      put:
        is: [ validate ]
        body:
          application/json:
            type: holdingsRecord
            example:
              strict: false
              value: !include examples/holdings-storage/holdingsRecord_get.json