#%RAML 1.0
title: Inventory Storage Holdings Batch Synchronous Unsafe API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: "Inventory Storage Holdings Batch Sync Unsafe API"
    content: <b>Batch API for synchronously uploading holdings records into the inventory with optimistic locking disabled</b>

types:
  errors: !include raml-util/schemas/errors.schema
  holdingsrecords_post: !include schemas/holdings-storage/holdingsRecords_post.json
/holdings-storage/batch/synchronous-unsafe:
  displayName: Holdings Batch Upload Sync API With Optimistic Locking Disabled
  post:
    description: "Create or update a collection of holdings in a single synchronous request; if any holding fails the complete batch will be rejected (all or nothing). Environment variable DB_ALLOW_SUPPRESS_OPTIMISTIC_LOCKING is required, see https://github.com/folio-org/raml-module-builder#environment-variables for details. The _version property is ignored, optimistic locking is disabled - this is known to lead to data loss in some cases, don't use in production, you have been warned!"
    body:
      application/json:
        type: holdingsrecords_post
        example: !include examples/holdings-storage/holdingsRecords_post.json
    responses:
      201:
        description: "All holdings have been successfully created or updated"
      413:
        description: "Payload too large or not allowed by DB_ALLOW_SUPPRESS_OPTIMISTIC_LOCKING environment variable"
        body:
          text/plain:
            example: "Payload Too Large"
      422:
        description: "Unprocessable Entity"
        body:
          application/json:
            type: errors
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
