#%RAML 1.0
title: Inventory Storage Holdings Batch Synchronous API
version: v1.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: "Inventory Storage Holdings Batch Sync API"
    content: <b>Batch API for synchronously uploading holdings records into the inventory</b>

types:
  errors: !include raml-util/schemas/errors.schema
  holdingsRecordsPostRequest: !include schemas/holdings-storage/holdingsRecords_post.json
/holdings-storage/batch/synchronous:
  displayName: Holdings Batch Upload Sync API
  post:
    description: "Create or update a collection of holdings in a single synchronous request; if any holding fails the complete batch will be rejected (all or nothing)"
    queryParameters:
      upsert:
        description: When a record with the same id already exists upsert=true will update it, upsert=false will fail the complete batch. The _version property of each holding to be updated must match the stored _version property (optimistic locking).
        type: boolean
        required: false
        default: false
    body:
      application/json:
        type: holdingsRecordsPostRequest
        example: !include examples/holdings-storage/holdingsRecords_post.json
    responses:
      201:
        description: "All holdings have been successfully created or updated"
      409:
        description: "Optimistic locking version conflict"
        body:
          text/plain:
            example: "version conflict"
      413:
        description: "Payload Too Large"
        body:
          text/plain:
            example: "Payload Too Large"
      422:
        description: "Unprocessable Entity"
        body:
          application/json:
            type: errors
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
