#%RAML 0.8
title: Instance Identifier Types API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Identifier Types API
    content: This documents the API calls that can be made to query and manage instance identifier types

schemas:
  - identifiertype.json: !include identifiertype.json
  - identifierTypes: !include identifiertypes.json
  - errors: !include raml-util/schemas/errors.schema
  - error.schema: !include raml-util/schemas/error.schema
  - parameters.schema: !include raml-util/schemas/parameters.schema

traits:
  - secured: !include raml-util/traits/auth.raml
  - pageable: !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml
  - validate: !include raml-util/traits/validation.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml
  - get-delete-only: !include raml-util/rtypes/get-delete.raml

/identifier-types:
  type:
    collection:
      exampleCollection: !include examples/identifiertypes.json
      exampleItem: !include examples/identifiertype.json
      schemaCollection: identifierTypes
      schemaItem: identifiertype.json
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of identifier types
  post:
    description: Create a new identifier type
    is: [validate]
  /{identifierTypeId}:
    description: Pass in the identifier type id
    type:
      collection-item:
        exampleItem: !include examples/identifiertype.json
        schema: identifiertype.json
