#%RAML 1.0
title: ILL policy API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://github.com/org/folio/mod-inventory-storage

documentation:
  - title: ILL policy API
    content: This documents the API calls that can be made to query and manage ILL policies of the system

types:
  illPolicy: !include schemas/ill-policies/illpolicy.json
  illPolicies: !include schemas/ill-policies/illpolicies.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/ill-policies:
  type:
    collection:
      exampleCollection: !include examples/illpolicies.json
      exampleItem: !include examples/illpolicy.json
      schemaCollection: illPolicies
      schemaItem: illPolicy
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of ILL policy types
  post:
    description: Create a new ILL policy
    is: [validate]
  /{id}:
    description: "Pass in the ILL policy id"
    type:
      collection-item:
        exampleItem: !include examples/illpolicy.json
        schema: illPolicy
