#%RAML 1.0
title: Deprecated Inventory Storage Instance Batch API
version: v2.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: "Deprecated Inventory Storage Instance Batch API"
    content: <b>Deprecated Batch API for managing Inventory Instances, use /instance-storage/sync instead.</b>

types:
  errors: !include raml-util/schemas/errors.schema
  instances: !include instances.json
  instancesBatchResponse: !include instances-batch-response.json

/instance-storage/batch/instances:
  displayName: Deprecated Instances batch API, use /instance-storage/sync instead.
  post:
    description: "Create collection of instances in one request - deprecated, use /instance-storage/sync instead"
    body:
      application/json:
        type: instances
    responses:
      201:
        description: "At least one Instance from the list was created"
        body:
          application/json:
            type: instancesBatchResponse
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
          application/json:
            type: instancesBatchResponse
