#%RAML 1.0
title: Instance Relationship Types API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Instance Relationship Types API
    content: This documents the API calls that can be made to query and manage instance relationship types

types:
  instanceRelationshipType: !include instancerelationshiptype.json
  instanceRelationshipTypes: !include instancerelationshiptypes.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-delete-only: !include raml-util/rtypes/get-delete.raml

/instance-relationship-types:
  type:
    collection:
      exampleCollection: !include examples/instancerelationshiptypes.json
      exampleItem: !include examples/instancerelationshiptype.json
      schemaCollection: instanceRelationshipTypes
      schemaItem: instanceRelationshipType
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of relationship types
  post:
    description: Create a new relationship type
    is: [validate]
  /{relationshipTypeId}:
    description: Pass in the relationship type id
    type:
      collection-item:
        exampleItem: !include examples/instancerelationshiptype.json
        schema: instanceRelationshipType
