#%RAML 0.8
title: Instance Types API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Instance Types API
    content: This documents the API calls that can be made to query and manage instance resource types

schemas:
  - instancetype.json: !include instancetype.json
  - instanceTypes: !include instancetypes.json
  - errors: !include raml-util/schemas/errors.schema
  - error.schema: !include raml-util/schemas/error.schema
  - parameters.schema: !include raml-util/schemas/parameters.schema

traits:
  - secured: !include raml-util/traits/auth.raml
  - pageable: !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml
  - validate: !include raml-util/traits/validation.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml
  - get-delete-only: !include raml-util/rtypes/get-delete.raml

/instance-types:
  type:
    collection:
      exampleCollection: !include examples/instancetypes.json
      exampleItem: !include examples/instancetype.json
      schemaCollection: instanceTypes
      schemaItem: instancetype.json
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of instance types
  post:
    description: Create a new instance type
    is: [validate]
  /{instanceTypeId}:
    description: Pass in the instance type id
    type:
      collection-item:
        exampleItem: !include examples/instancetype.json
        schema: instancetype.json
