#%RAML 1.0
title: Instance Formats API
version: v2.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Instance Formats API
    content: This documents the API calls that can be made to query and manage instance formats

types:
  instanceFormat: !include instanceformat.json
  instanceFormats: !include instanceformats.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-delete-only: !include raml-util/rtypes/get-delete.raml

/instance-formats:
  type:
    collection:
      exampleCollection: !include examples/instanceformats.json
      exampleItem: !include examples/instanceformat.json
      schemaCollection: instanceFormats
      schemaItem: instanceFormat
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of instance formats
  post:
    description: Create a new instance format
    is: [validate]
  /{instanceFormatId}:
    description: Pass in the instance format id
    type:
      collection-item:
        exampleItem: !include examples/instanceformat.json
        schema: instanceFormat
