#%RAML 1.0
title: Inventory Storage Instance Batch Sync API
version: v3.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: "Inventory Storage Instance Batch Sync API"
    content: <b>Batch API for synchronously uploading instances into the inventory</b>

types:
  errors: !include raml-util/schemas/errors.schema
  instancesPostRequest: !include schemas/instance-storage/instances_post.json
/instance-storage/batch/synchronous:
  displayName: Instances Batch Upload Sync API
  post:
    description: "Create or update a collection of instances in a single synchronous request; if any instance fails the complete batch will be rejected (all or nothing)"
    queryParameters:
      upsert:
        description: When a record with the same id already exists upsert=true will update it, upsert=false will fail the complete batch. The _version property of each instance to be updated must match the stored _version property (optimistic locking).
        type: boolean
        required: false
        default: false
    body:
      application/json:
        type: instancesPostRequest
        example: !include examples/instances_post.json
    responses:
      201:
        description: "All instances have been successfully created or updated"
      409:
        description: "Optimistic locking version conflict"
        body:
          text/plain:
            example: "version error"
      413:
        description: "Payload Too Large"
        body:
          text/plain:
            example: "Payload Too Large"
      422:
        description: "Unprocessable Entity"
        body:
          application/json:
            type: errors
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
