#%RAML 1.0
title: Preceding/succeeding Titles API
version: v0.1
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Preceding/succeeding Titles API
    content: <b>Storage for preceding/succeeding titles in the inventory</b>

types:
  precedingSucceedingTitle: !include instanceprecedingsucceedingtitle.json
  precedingSucceedingTitles: !include instanceprecedingsucceedingtitles.json
  errors: !include raml-util/schemas/errors.schema

traits:
  language: !include raml-util/traits/language.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/preceding-succeeding-titles:
    displayName: Preceding/Succeeding titles
    type:
      collection:
        exampleCollection: !include  examples/precedingsucceedingtitles_get.json
        schemaCollection: precedingSucceedingTitles
        schemaItem: precedingSucceedingTitle
        exampleItem: !include  examples/precedingsucceedingtitle_get.json
    get:
      is: [pageable,
          searchable: {description: "by preceding instance ID or by succeeding instance ID (using CQL))",
                       example: "precedingInstanceId==83a50dc6-b887-43d9-93ee-28b2c4cd11f8
                                 succeedingInstanceId==30fcc8e7-a019-43f4-b642-2edc389f4501"},
          ]
      description: Return a list of preceding succeeding titles
    post:
      description: Create a new preceding/succeeding title
      is: [validate]
    /{precedingSucceedingTitleId}:
      type:
        collection-item:
          exampleItem: !include examples/precedingsucceedingtitle_get.json
          schema: precedingSucceedingTitle
      get:
        description: Get a preceding/succeeding title by id
      put:
        description: Update a preceding/succeeding title by id
        is: [validate]
      delete:
        description: Delete a preceding/succeeding title by id
