#%RAML 1.0
title: Inventory Reindex Records API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

traits:
  validate: !include raml-util/traits/validation.raml

types:
  publishReindexRecords: !include reindex-records/publishReindexRecords.json
  errors: !include raml-util/schemas/errors.schema

/inventory-reindex-records/publish:
  displayName: Inventory Storage Reindex Records Publish API
  post:
    description: Publish inventory storage reindex records.
    is: [ validate ]
    body:
      application/json:
        type: publishReindexRecords
        example:
          strict: false
          value: ../examples/reindex-records/publishReindexRecords.json
    responses:
      201:
        description: "Records of the given range were published for reindex"
      400:
        description: "Bad request: malformed request body"
      401:
        description: "Not authorized to perform requested action"
        body:
          text/plain:
            example: "unable to retrieve records -- unauthorized"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "internal server error, contact administrator"
