#%RAML 1.0
title: Inventory Storage View API
version: v2.0
protocols: [ HTTP, HTTPS ]
baseUri: http://github.com/org/folio/mod-inventory-storage

documentation:
  - title: Inventory view
    content: Inventory view endpoints

types:
  inventoryViewInstance: !include inventory-view-instance.json
  idsRequest: !include ids-request.json
  errors: !include raml-util/schemas/errors.schema

traits:
  validate: !include raml-util/traits/validation.raml
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml

resourceTypes:
  collection-stream: !include raml-util/rtypes/collection-stream.raml

/inventory-view/instances:
  type:
    collection-stream:
     schemaCollection: inventoryViewInstance
     exampleCollection: !include examples/inventory-view-instances.json
  get:
    description: Get instances by id with their holdings and items
    is: [pageable, searchable: {description: "using CQL",
                      example: "title=\"*uproot*\""}]
  post:
    description: Return Instances by id with their holdings and items
    is: [validate]
    body:
      application/json:
        type: idsRequest


