#%RAML 1.0
title: Item Storage Dereferenced
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Item Retrieval API
    content: <b>Get dereferenced items data from inventory</b>

types:
  dereferencedItem: !include dereferenceditem.json
  dereferencedItems: !include dereferenceditems.json
  dereferencedItemWithoutPubPeriod: !include dereferenceditem-without-pub-period.json
  dereferencedItemsWithoutPubPeriod: !include dereferenceditems-without-pub-period.json

  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection-get.raml
  collection-item: !include raml-util/rtypes/item-collection-get.raml

/item-storage-dereferenced:
  /items:
    type:
      collection:
        exampleCollection: !include examples/items_dereferenced_get.json
        schemaCollection: dereferencedItemsWithoutPubPeriod
    get:
      is: [pageable,
         searchable: {description: "using CQL (indexes for item and material type)",
                        example: "title=\"*uproot*\""},
          ]
    /{itemId}:
      type:
        collection-item:
          exampleItem: !include examples/item_dereferenced_get.json
          schema: dereferencedItemWithoutPubPeriod
      get:
