#%RAML 1.0
title: Inventory Storage Item Batch Sync Unsafe API
version: v2.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: "Inventory Storage Item Batch Sync Unsafe API"
    content: <b>Batch API for synchronously uploading items into the inventory</b>

types:
  errors: !include raml-util/schemas/errors.schema
  itemsPostRequest: !include schemas/item-storage/items_post.json
/item-storage/batch/synchronous-unsafe:
  displayName: Item Batch Upload Sync API With Optimistic Locking Disabled
  post:
    description: "Create or update (upsert) a collection of items in a single synchronous request; if any item fails the complete batch will be rejected (all or nothing). Environment variable DB_ALLOW_SUPPRESS_OPTIMISTIC_LOCKING is required, see https://github.com/folio-org/raml-module-builder#environment-variables for details. The _version property is ignored, optimistic locking is disabled - this is known to lead to data loss in some cases, don't use in production, you have been warned!"
    body:
      application/json:
        type: itemsPostRequest
        example: !include examples/items_post.json
    responses:
      201:
        description: "All items have been successfully created or updated"
      413:
        description: "Payload too large or not allowed by DB_ALLOW_SUPPRESS_OPTIMISTIC_LOCKING environment variable"
        body:
          text/plain:
            example: "Payload Too Large"
      422:
        description: "Unprocessable Entity"
        body:
          application/json:
            type: errors
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
