#%RAML 1.0
title: Location API
version: v3.1
protocols: [ HTTP, HTTPS ]
baseUri: http://github.com/org/folio/mod-inventory-storage

documentation:
  - title: Locations API
    content: This documents the API calls that can be made to query and manage
      (shelf) locations of the system

types:
  location: !include locations/location.json
  locations: !include locations/locations.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml
  get-delete-only: !include raml-util/rtypes/get-delete.raml

/locations:
  type:
    collection:
      exampleCollection: !include examples/locations/locations.json
      exampleItem: !include examples/locations/location.json
      schemaCollection: locations
      schemaItem: location
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of locations
    queryParameters:
      includeShadowLocations:
        description: Whether to include shadow locations in the response or not.
        type: boolean
        required: false
        default: false
  post:
    description: Create a new location
    is: [validate]
  delete:
    description: "Delete all locations"
    responses:
      204:
        description: "All locations deleted"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  /{id}:
    description: "Pass in the  location id"
    type:
      collection-item:
        exampleItem: !include examples/locations/location.json
        schema: location
    get:
    put:
      description: Update a location by id
      is: [validate]
    delete:
