#%RAML 1.0
title: Inventory Storage Record Bulk API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://github.com/org/folio/mod-inventory-storage

documentation:
  - title: Inventory Storage records Bulk Download API
    content: <b>API for downloading a bulk set of instances or holdings IDs</b>

types:
  ids: !include schemas/ids.json
  errors: !include raml-util/schemas/errors.schema

traits:
  orderable: !include raml-util/traits/orderable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml
  pageable: !include raml-util/traits/pageable.raml

resourceTypes:
  collection-get: !include raml-util/rtypes/collection-get.raml

/record-bulk:
  /ids:
    displayName: Records ID Bulk Download API
    type:
      collection-get:
        schemaCollection: ids
        exampleCollection: !include examples/ids.json
    get:
      description: Retrieve a list of record IDs.
      is: [
        searchable: {description: "with valid searchable fields", example: "name=aaa"},
        validate,
        pageable
      ]
      queryParameters:
        field:
          description: Field
          type: string
          enum: [id]
          default: id
          required: false
        recordType:
          description: Determines which record type UUIDs should be fetched
          type: string
          enum: [INSTANCE, HOLDING]
          default: INSTANCE
          required: false
        limit:
          default: 2147483647
