#%RAML 1.0
title: Service Points API
version: v3.5
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Service Points API
    content: This documents the API calls that can be made to query and manage service points in the system

types:
  servicepoint: !include schemas/servicepoint.json
  servicepoints: !include schemas/servicepoints.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/service-points:
  type:
    collection:
      exampleCollection: !include examples/servicepoints.json
      exampleItem: !include examples/servicepoint.json
      schemaCollection: servicepoints
      schemaItem: servicepoint
  get:
    is: [
      searchable: { description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    queryParameters:
      includeRoutingServicePoints:
        description: "Should ECS request routing service points be included in the response"
        default: false
        required: false
        type: boolean
    description: Return a list of service points
  post:
    description: Create a new service point
    is: [validate]
    responses:
      422:
        description: "Validation error"
        body:
          application/json:
            type: errors
  delete:
    description: "Delete all service points"
    responses:
      204:
        description: "All service points delete"
      500:
        description: "Internal server error"
        body:
          text/plain:
            example: "Internal server error"
  /{servicepointId}:
    description: Pass the id for the service point
    type:
      collection-item:
        exampleItem: !include examples/servicepoint.json
        schema: servicepoint
    put:
        description: Update a service point
        is: [validate]
        responses:
          422:
            description: "Validation error"
            body:
              application/json:
                type: errors
