#%RAML 1.0
title: Statistical code type reference API
version: v1.0
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Statistical code type reference API
    content: This documents the API calls that can be made to query and manage statistical code types of the system

types:
  statisticalCodeType: !include schemas/statistical-code-types/statisticalcodetype.json
  statisticalCodeTypes: !include schemas/statistical-code-types/statisticalcodetypes.json
  errors: !include raml-util/schemas/errors.schema

traits:
  pageable: !include raml-util/traits/pageable.raml
  searchable: !include raml-util/traits/searchable.raml
  validate: !include raml-util/traits/validation.raml

resourceTypes:
  collection: !include raml-util/rtypes/collection.raml
  collection-item: !include raml-util/rtypes/item-collection.raml

/statistical-code-types:
  type:
    collection:
      exampleCollection: !include examples/statisticalcodetypes.json
      exampleItem: !include examples/statisticalcodetype.json
      schemaCollection: statisticalCodeTypes
      schemaItem: statisticalCodeType
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of statistical code types
  post:
    description: Create a new statistical code type
    is: [validate]
  delete:
    description: "Delete all statistical code types"
    responses:
      204:
        description: "All statistical code types deleted"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  /{statisticalCodeTypeId}:
    description: Pass in statistical code type ID
    type:
      collection-item:
        exampleItem: !include examples/statisticalcodetype.json
        schema: statisticalCodeType

