#%RAML 0.8
title: Statistical code reference API
version: v2.2
protocols: [ HTTP, HTTPS ]
baseUri: http://localhost

documentation:
  - title: Statistical code reference API
    content: This documents the API calls that can be made to query and manage statistical codes of the system

schemas:
  - statisticalcode.json: !include statisticalcode.json
  - statisticalCodes: !include statisticalcodes.json
  - errors: !include raml-util/schemas/errors.schema
  - error.schema: !include raml-util/schemas/error.schema
  - parameters.schema: !include raml-util/schemas/parameters.schema
  - raml-util/schemas/metadata.schema: !include raml-util/schemas/metadata.schema

traits:
  - secured: !include raml-util/traits/auth.raml
  - pageable: !include raml-util/traits/pageable.raml
  - searchable: !include raml-util/traits/searchable.raml
  - language: !include raml-util/traits/language.raml
  - validate: !include raml-util/traits/validation.raml

resourceTypes:
  - collection: !include raml-util/rtypes/collection.raml
  - collection-item: !include raml-util/rtypes/item-collection.raml
  - get-delete-only: !include raml-util/rtypes/get-delete.raml

/statistical-codes:
  type:
    collection:
      exampleCollection: !include examples/statisticalcodes.json
      exampleItem: !include examples/statisticalcode.json
      schemaCollection: statisticalCodes
      schemaItem: statisticalcode.json
  get:
    is: [
      searchable: {description: "with valid searchable fields", example: "name=aaa"},
      pageable
    ]
    description: Return a list of statistical codes
  post:
    description: Create a new statistical code
    is: [validate]
  delete:
    description: "Delete all statistical codes"
    responses:
      204:
        description: "All statistical codes deleted"
      500:
        description: "Internal server error, e.g. due to misconfiguration"
        body:
          text/plain:
            example: "Internal server error, contact administrator"
  /{statisticalCodeId}:
    description: Pass in statistical code ID
    type:
      collection-item:
        exampleItem: !include examples/statisticalcode.json
        schema: statisticalcode.json

